### ISSUE TITLE
Batch file permissions

### ISSUE THREAD

**Issue by svnpenn** [Alexpux/MSYS2-packages#222]
These files have bad default permissions

~~~
$ ls -l *.bat
-rw-r--r--+ 1 Steven None   68 Nov  7 03:46 autorebase.bat
-rw-r--r--+ 1 Steven None  602 Nov  7 03:46 autorebasebase1st.bat
-rw-r--r--+ 1 Steven None 1263 Dec  8 05:04 mingw32_shell.bat
-rw-r--r--+ 1 Steven None 1263 Dec  8 05:04 mingw64_shell.bat
-rw-r--r--+ 1 Steven None 1260 Dec  8 05:04 msys2_shell.bat
~~~

If you try to run them, you get

> Windows cannot access the specified device, path, or file. You may not have
> the appropriate permissions to access the item.

**Comment by elieux** [comment]
I never had such problem. Where did you install MSYS2? Can you post output of `icacls /msys2_shell.bat | cat`?

**Comment by svnpenn** [comment]
1. Download msys2-base-x86_64-XXXXXXXX.tar.xz
2. Extract using tar
3. Try to run one of the bat files

**Comment by svnpenn** [comment]
Look, you can even see it in 7-Zip

![bad][1]
[1]:
https://cloud.githubusercontent.com/assets/926619/7211928/cb220076-e525-11e4-97d7-db7f22ceea25.png

**Comment by elieux** [comment]
The missing `x` is not a problem. I also have `-rw-r--r--`, but I'm able to run the batch files both from Windows and from inside MSYS2.

**Comment by elieux** [comment]
The `+` in your listing is more interesting. If I'm not mistaken, it suggests there's something more in the DACLs of those files. That's why I wanted the `icacls` output.

**Comment by svnpenn** [comment]
@elieux the only thing that matters in this issue is that the `x` permission is
not set on these files as it should be.

- If you extract the `.tar.xz` with 7-Zip, it is not an issue because 7-Zip does
  not respect POSIX permissions.

- If you extract with a program like tar that respects POSIX permissions, then
  you correct will not be able to run the files, because they are not executable
  as I have shown.

**Comment by elieux** [comment]
I'm not able to reproduce the error. I downloaded the latest 64-bit tar.xz, put it into `/home/`, extracted using `bsdtar -xf` and ran `msys64/msys2_shell.bat` without problems.

**Comment by svnpenn** [comment]
@elieux I dont need you to be able to reproduce the error. As my picture shows,
I have already proven that the executable permission has not been set on these
files. Using 7-Zip browser without even extracting you can see the problem.

No discussion is left to be done other than to fix the problem.

**Comment by elieux** [comment]
I was able to reproduce the issue once I disabled ACL inheritance on the containing directory. I'm not sure how many people run MSYS2 in such a way, but I'll try to whip up a patch.

**Comment by svnpenn** [comment]
You should read up on the changes to Cygwin permissions, as they will trickle
down to MSYS2 soon enough.

http://cygwin.com/ml/cygwin/2015-04/msg00392.html

**Comment by elieux** [comment]
I've been following the ML for some time, thank you. AFAIK our current install and upgrade process doesn't reset any permissions so we should still be in the clear after the 2.0 release.

**Comment by elieux** [comment]
With regard to our package building process, I think the correct solution for us would be if Cygwin recognized .bat files as executable, but I'm not currently inclined to invest the time into it as no-one else reported such problems. I'll try asking around on IRC tomorrow.

May I bother you to tell me how and why you encountered this problem?

**Comment by elieux** [comment]
With regard to our package building process, I think the correct solution for us would be if Cygwin recognized .bat files as executable, but I'm not currently inclined to invest the time into it as no-one else reported such problems so far and I'm not convinced that it will become a global problem after the 2.0 release. I'll try asking around on IRC tomorrow.

May I bother you to tell me how and why you encountered this problem or how the 2.0 changes affect this?

**Comment by svnpenn** [comment]
On Linux if you want to execute a file it must have the correct permissions.
By default a `touch`ed file will not have this, for security reasons.

However Windows has a wrong-headed take on this, in that a file create with
`New` > `Text Document` automatically has execute permissions.

So what looks to have happened in this case is that whoever created the batch
files did so in a MSYS2 environment, hence the correct lack of execute
permission. What they did not do is `chmod +x` to correct give these files
execute permission, as would have been done if the files were created with
Windows Native tools.

I really dont want to keep discussing this. Whether or not these files run for
anyone is beside the point. The point is that they have the **wrong**
permissions, which in some cases will make it impossible to be run. Please lets
drop the discussion and just fix, or refuse to fix, the problem.

**Comment by elieux** [comment]
I sent a PR that should fix this.

**Comment by svnpenn** [comment]
@elieux what does a colon have to do with file permissions?

**Comment by elieux** [comment]
It persuades Cygwin to put the `x` bits into the file's mode on `noacl` mounts. Since MSYS2 mounts are set to `noacl` by default and all packaging happens inside MSYS2, this is probably the easiest way to comply with your request.

**Comment by svnpenn** [comment]
How can I make it any clearer? All that needs to be done is `chmod +x` on these files. Your patch does not do that, and does not fix the problem of the files having the wrong permissions.

**Comment by elieux** [comment]
Have you even tried it? `chmod +x` doesn't have any effect on `noacl` mounts.

**Comment by svnpenn** [comment]
- This is not about MSYS2
- This is not about icacls
- This is not about DACLs
- This is not about bsdtar
- This is not about some colon header
- This is not about noacl mounts

All of your comments have not been able to divert my attention from the fact
that these files have the wrong permissions. This is a fact, and it is
undisputed.

**Comment by mingwandroid** [comment]
As @elieux said, MSYS2 uses `noacl` on its mounts, therefore what you think you know about how the Cygwin ACL code and recent changes relates to MSYS2 is incorrect.

So for MSYS2, the function `has_exec_chars` is the only thing that decides if a file is executable or not. This function looks for ":\n", so that's what @elieux has fixed.

Now, when Alexey next builds the root filesystem package, this problem will go away and your files will be executable.

Please don't be rude to our volunteers who have graciously spent time on the weekend to help you out. It reflects badly on you, not them.

**Comment by svnpenn** [comment]
@mingwandroid please consider that I do not care how it might reflect on me, I
care about the correctness of the repository.

As my picture has shown, these permissions are wrong and a colon is not going to
change that. If you extract `msys2-base-x86_64-XXXXXXXX.tar.xz` with latest
Cygwin tar, those batch files are **not executable**. If you two want to keep
your head in the sand, that is your own business.

**Comment by mingwandroid** [comment]
As I said, when @alexpux rebuilds this package your problem will go away. If you want it fixed more quickly than that, you can build the package yourself.

My request that you exhibit manners stands.
